languageCode = "en"
languageName = "English"
weight = 1
title = "Kevin Chiu"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "Kevin Chiu"
dateFormat = "2 January 2006"
author = { name = "Kevin Chiu", image = "orange_logo.jpeg", headline = "Things are only impossible until they're not.", bio = "", links = [ { instagram = "https://instagram.com/kevingc" }, { facebook = "https://fb.com/kevinchiu" }, { x-twitter = "https://twitter.com/kevingc" }, { github = "https://github.com/kevinchiu" } ] }
logo = "face_logo_small.png"
secondaryLogo = "face_logo_small.png"
